package configs

// General Success
const Success = "000"
const Paymentprocess = "001"
const Decryptfailed = "100"
const Invalidparentformat = "101"
const Invalidchildformat = "102"
const Dataexpired = "103"
const Encryptfailed = "104"
const Invalidhasheddata = "105"
const Invalidencrypteddata = "106"
const Invalidformat = "108"
const Invalidipaddress = "109"
const Invalidaccesstoken = "116"
const Incorrectcredential = "117"
const Paymentfailed = "121"
const Invalidamount = "122"
const Numberonly = "124"
const Responsecannotbeparsed = "333"
const Badrequest = "400"
const Authenticationfailed = "401"
const Nodata = "404"
const Notallowed = "405"
const Validationfailed = "422"
const Validateparamfailed = "423"
const Maxrequest = "429"
const Internalerror = "500"
const VaNotRegistered = "501"
const Requestfailed = "600"
const InvalidVaType = "667"
const VaPaid = "669"

// Systemmaintenance Use To Maintenance System / Shutdown All Api
const Systemmaintenance = "606"
const InvalidPrefix = "665"

// Error From Biller (No Connection / System Down)
const Errtokenbiller = "701"
const Errinqbiller = "702"
const Errpaybiller = "703"
const Errinqstatbiller = "704"
const Errflagbiller = "705"
const Paymentsuccessful = "806"
const Verificationsuccess = "807"
const Invalidparam = "901"
const Test = "999"
